AWSTemplateFormatVersion: 2010-09-09
Description: Antifact Store

Outputs:
  BucketService1:
    Value: !Ref BucketService1
  BucketService2:
    Value: !Ref BucketService2


Resources:

  BucketService1:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: antifact-service-1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketService2:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: antifact-service-2
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
